### ISSUE TITLE
Możliwość zaznaczenia kursu mimo, że koliduje z innym

### ISSUE THREAD

**Issue by baatochan** [Diegos962/Zapisownik-PWR#1]
Proponuje dodać opcje możliwości zaznaczenia kursu mimo, że koliduje on z innym. 

Bardzo często zapisuje się jednocześnie na laborki (co 2 tyg) mimo, że w tym samym terminie mam co tydzień wykład. 

Mogłoby być jakieś dodatkowe ostrzeżenie czy coś, ale fajnie jakby taka opcja była.

**Comment by Diegos962** [comment]
W ewentualnej kolejnej wersji planuję dodać taką możliwość.
