### ISSUE TITLE
Przyciski zapisz i wczytaj plan na głównym ekranie nie działają na Win10

### ISSUE THREAD

**Issue by baatochan** [Diegos962/Zapisownik-PWR#2]
Przyciski zapisz i wczytaj plan na głównym ekranie nie działają na Win10

**Comment by Diegos962** [comment]
A jak ich używasz? Może źle zrozumiałeś, do czego służą? To są tymczasowe opcje i nie operują one na plikach. Możesz np. wybrać sobie cześć planu, zapisać tymczasowo, następnie dolosować plan, a jeśli ci się on nie podoba, to wczytać ten tymczasowy i ponownie dolosować, itd.

**Comment by baatochan** [comment]
Okej, to issue closed. Próbowałem uzywac na plikach. 

Przydałaby się natomiast jakaś info o tym, np w wyskakującym po najechaniu dymku.

**Comment by Diegos962** [comment]
Info po najechaniu jest (przynajmniej u mnie), tylko trzeba chwilę poczekać. Zamykam.
